### PR TITLE
Update Jetty to 9.3.8

### PR DESCRIPTION
**Pull request by MartinMoizard**

### CODE REVIEW

**Comment by md5** [comment]
Thanks @MartinMoizard!  Looks good to me.

**Comment by MartinMoizard** [comment]
@md5 thanks! How does it work to push a new tag on Docker Hub?

**Comment by md5** [comment]
I've created https://github.com/docker-library/official-images/pull/1545 to get it merged. Depending on the Official Image team's workload, it will probably be pushed in a few hours. I'll ping them if it doesn't happen today.

**Comment by md5** [comment]
For reference, the process is to make a PR to `docker-library/official-images`. I use `make library` for this purpose to update the `library/jetty` file in that repository. The Official Images team then builds and tests the image before pushing to Docker Hub.

**Comment by MartinMoizard** [comment]
Ok :) Thank you for the explanation.

**Comment by md5** [comment]
@MartinMoizard BTW, if there are pressing reasons to get that version up to Docker Hub, I can ask to have the push expedited, but I didn't see any release announcement or notes for 9.3.8 to make me think it's security-critical or something like that.

**Comment by MartinMoizard** [comment]
@md5 we faced the issue fixed by https://github.com/eclipse/jetty.project/pull/364 but that's ok to wait until it's merged on the official docker images repo

**Comment by md5** [comment]
@MartinMoizard The 9.3.8 image is live on Docker Hub. It was pushed earlier today.

**Comment by gregw** [comment]
@md5 No not security critical, just a bunch of moderate bug fixes.  Was just on my way over to update here... but you guys to fast for me!

**Pull request merged**
