### PR TITLE
upgrade to jetty-9.4.18

### PR DESCRIPTION
**Pull request by gregw**
This version fixes several CVEs

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by md5** [comment]
It looks like only one of the 9.4 variants is updated in this PR. Is there any reason for the jre8 variant for Alpine and the jre11 variant for Debian to not also be updated?

**Comment by gregw** [comment]
... there is a reason... I'm an idiot! stand by...

**Comment by md5** [comment]
Still missing Alpine. Assuming `make update` still works, I'd probably just run that and see what it updates.

**Comment by gregw** [comment]
Alpine was done for jre8 (doesn't exit for jre11).
I did an update anyway as there are now 9.2 and 9.3 updates.

**Review by md5 — APPROVED** [review]

**Comment by md5** [comment]
Opened https://github.com/docker-library/official-images/pull/5846

**Pull request merged**
