### PR TITLE
update to 9.4.13.v20181111

### PR DESCRIPTION
**Pull request by gregw**
update to 9.4.13.v20181111
Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Review by md5 — APPROVED** [review]
I submitted a review this morning... Not sure why it didn't take. It looks like the CI failures are transient and should resolve with a retry.

**Comment by gregw** [comment]
I'm going to hold off on this... as it appears that 9.4.13 may be a bad release and have a bad bug in it.    Thus hopefully we will have a 9.4.14 in a day or two, and I will then progress both at the same time (as I think we should have the 9.4.13 for completeness..  just not recommend it for use in most circumstances).

**Comment by md5** [comment]
@gregw I'm not sure the best way to do that and still avoid having people download it as "9.4" during a small window. Also, I think there are other gaps in the Docker image version history for this image.

I would be inclined to skip the Docker image for 9.4.13.

@tianon thoughts?

**Comment by tianon** [comment]
No opinion here -- if skipping 9.4.13 doesn't bother y'all, it's no problem for us. :+1:

**Comment by gregw** [comment]
Let's skip 13... it's really living up to it's bad luck number and is a bit of a disaster of a release on several fronts!  14 a few days away.

**Pull request closed without merging**
